name: amd-monai
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - numpy>=1.24,<3.0
  - pytorch-triton-rocm
  - torchio
  - torchvision
  - pip
  - pip:
    - -r requirements-dev.txt
